name: Publish a release

on:
  push:
    tags:
      - '*'

concurrency:
  group: "release-${{ github.ref }}"
  cancel-in-progress: false

env:
  ORG_GRADLE_PROJECT_VERSION_NAME: ${{ github.ref_name }}
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID }}
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}
  GRADLE_OPTS: -Dkotlin.incremental=false -Dorg.gradle.daemon=false -Dorg.gradle.vfs.watch=false -Dorg.gradle.logging.stacktrace=full

jobs:
  publish_archives:
    runs-on: macos-latest
    if: github.repository == 'wireapp/sqldelight'
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: .github/workflows/.ci-java-version
      - uses: gradle/actions/setup-gradle@v6
        with:
          cache-cleanup: always

      - run: ./gradlew publishToMavenLocal
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}

      - run: ./gradlew publishToMavenCentral --no-parallel
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}

  publish_npm_packages:
    runs-on: ubuntu-latest
    if: github.repository == 'wireapp/sqldelight'
    permissions:
      contents: read
      id-token: write
    needs: publish_archives

    steps:
      - uses: actions/checkout@v6
      - name: Create Gradle files
        run: |
          cd ~
          mkdir -p .gradle/ && touch .gradle/gradle.properties
      - uses: actions/setup-java@v5
        id: setup-java
        with:
          distribution: 'zulu'
          java-version-file: .github/workflows/.ci-java-version
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - name: Setup Gradle Java installations paths
        run: |
          cd ~/.gradle
          echo "org.gradle.java.installations.paths=${{ steps.setup-java.outputs.path }}" >> gradle.properties
      - uses: gradle/actions/setup-gradle@v6
        with:
          cache-cleanup: always

      - name: Get Version
        run: echo "VERSION_NAME=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
        id: version

      - name: Assemble NPM Packages
        run: ./gradlew :drivers:web-worker-driver:sqljs:assemblePackage

      - name: Publish SNAPSHOT Packages
        working-directory: drivers/web-worker-driver/sqljs/build/package
        if: ${{ success() && contains(steps.version.outputs.VERSION_NAME, 'SNAPSHOT') }}
        run: npm publish --tag snapshot

      - name: Publish Packages
        working-directory: drivers/web-worker-driver/sqljs/build/package
        if: ${{ success() && !contains(steps.version.outputs.VERSION_NAME, 'SNAPSHOT') }}
        run: npm publish

  publish_release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - publish_archives
      - publish_npm_packages
    steps:
      - uses: actions/checkout@v6

      - name: Extract release notes
        id: release_notes
        uses: ffurrer2/extract-release-notes@v3

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          body: ${{ steps.release_notes.outputs.release_notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
